# Generated by Django 5.2.6 on 2025-09-25 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='custom_resume',
            field=models.FileField(blank=True, help_text='Upload a custom resume for this application (optional)', null=True, upload_to='resumes/applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload PDF or Word document only', null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
