# Generated by Django 4.2.7 on 2025-12-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_ats_phase3_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="company_linkedin",
            field=models.URLField(blank=True, help_text="Company LinkedIn page URL"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="Your LinkedIn profile URL (e.g., https://linkedin.com/in/yourname)",
            ),
        ),
    ]
