# Generated by Django 4.2.7 on 2025-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_add_linkedin_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Brief summary about yourself"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="desired_title",
            field=models.CharField(
                blank=True, help_text="Job title you are looking for", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Your location (city, state)", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_searchable",
            field=models.BooleanField(
                default=True,
                help_text="Allow employers to find your profile in candidate search",
            ),
        ),
    ]
