# Generated by Django 4.2.7 on 2025-12-31 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0011_userprofile_bio_userprofile_desired_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymous session identifier",
                        max_length=64,
                    ),
                ),
                ("user_message", models.TextField()),
                ("ai_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hashed IP for anonymous tracking",
                        max_length=64,
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="API response time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "was_helpful",
                    models.BooleanField(
                        blank=True, help_text="User feedback if provided", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Log",
                "verbose_name_plural": "Chat Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
