# Generated by Django 4.2.7 on 2026-01-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_add_chatlog_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="agency_name",
            field=models.CharField(
                blank=True,
                help_text="Name of your recruiting agency or company",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agency_website",
            field=models.URLField(
                blank=True, help_text="Your agency or company website"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allow_recruiter_contact",
            field=models.BooleanField(
                default=False,
                help_text="Allow verified recruiters to contact you about job opportunities",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_independent_recruiter",
            field=models.BooleanField(
                default=False,
                help_text="Check if you are an independent recruiter without a company affiliation",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_recruiter_approved",
            field=models.BooleanField(
                default=False, help_text="Admin approval status for recruiter accounts"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recruiter_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recruiter_linkedin_url",
            field=models.URLField(
                blank=True,
                help_text="Your personal LinkedIn profile URL (required for recruiter verification)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("employer", "Employer"),
                    ("recruiter", "Recruiter"),
                ],
                max_length=20,
            ),
        ),
    ]
