# Generated by Django 4.2.7 on 2026-01-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_add_recruiter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sms_consent",
            field=models.BooleanField(
                default=False,
                help_text="User has consented to receive SMS notifications",
            ),
        ),
    ]
