# Generated by Django 6.0.1 on 2026-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0015_add_2fa_and_traffic_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="application_deadline",
            field=models.DateField(
                blank=True, help_text="Optional deadline for applications", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("mid", "Mid Level"),
                    ("senior", "Senior Level"),
                    ("lead", "Lead/Manager"),
                    ("executive", "Executive"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When this job listing expires", null=True
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                    ("internship", "Internship"),
                    ("freelance", "Freelance"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="last_refreshed",
            field=models.DateTimeField(
                blank=True,
                help_text="When the employer last confirmed this job is still active",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_status",
            field=models.CharField(
                choices=[
                    ("on_site", "On-site"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default="on_site",
                max_length=20,
            ),
        ),
    ]
