# Generated by Django 6.0.1 on 2026-01-24 16:44

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def set_expiration_for_existing_jobs(apps, schema_editor):
    """Set expiration date for existing jobs that don't have one."""
    Job = apps.get_model('jobs', 'Job')
    default_expiration_days = 60

    # For existing jobs without an expiration date, set it to 60 days from now
    # (giving existing jobs time before they expire)
    now = timezone.now()
    expiration_date = now + timedelta(days=default_expiration_days)

    jobs_updated = Job.objects.filter(expires_at__isnull=True).update(
        expires_at=expiration_date
    )

    if jobs_updated:
        print(f'Set expiration date for {jobs_updated} existing job(s).')


def reverse_expiration(apps, schema_editor):
    """Reverse migration - set expires_at back to null."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.update(expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0016_add_job_expiration_and_type_fields"),
    ]

    operations = [
        migrations.RunPython(set_expiration_for_existing_jobs, reverse_expiration),
    ]
