# Generated by Django 5.2.6 on 2026-02-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_set_expiration_for_existing_jobs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("normalized_name", models.CharField(db_index=True, max_length=255)),
                ("website", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "company_size",
                    models.CharField(
                        blank=True, help_text="e.g., 51-200, 1001-5000", max_length=50
                    ),
                ),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_employer",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"userprofile__user_type": "employer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_company",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyHiringProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_active_listings", models.PositiveIntegerField(default=0)),
                ("total_historical_listings", models.PositiveIntegerField(default=0)),
                ("total_distinct_departments", models.PositiveIntegerField(default=0)),
                ("avg_listing_lifespan_days", models.FloatField(blank=True, null=True)),
                (
                    "median_listing_lifespan_days",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "listing_close_rate_30d",
                    models.FloatField(
                        blank=True,
                        help_text="Percentage of listings closed in last 30 days",
                        null=True,
                    ),
                ),
                ("net_job_movement_30d", models.IntegerField(default=0)),
                ("net_job_movement_90d", models.IntegerField(default=0)),
                (
                    "repost_frequency",
                    models.FloatField(
                        default=0.0, help_text="Average reposts per listing"
                    ),
                ),
                (
                    "boilerplate_ratio",
                    models.FloatField(
                        default=0.0,
                        help_text="Ratio of shared content across listings (0-1)",
                    ),
                ),
                ("avg_description_length", models.PositiveIntegerField(default=0)),
                ("has_salary_info_ratio", models.FloatField(default=0.0)),
                (
                    "reputation_score",
                    models.FloatField(
                        default=50.0, help_text="Composite reputation score (0-100)"
                    ),
                ),
                ("has_recent_layoffs", models.BooleanField(default=False)),
                ("glassdoor_rating", models.FloatField(blank=True, null=True)),
                (
                    "linkedin_followers",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "evergreen_listing_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Listings open > 90 days with no changes"
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hiring_profile",
                        to="jobs.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Hiring Profile",
                "verbose_name_plural": "Company Hiring Profiles",
            },
        ),
        migrations.CreateModel(
            name="ScrapedJobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ats",
                    models.CharField(
                        choices=[
                            ("greenhouse", "Greenhouse"),
                            ("lever", "Lever"),
                            ("workday", "Workday"),
                            ("icims", "iCIMS"),
                            ("taleo", "Taleo"),
                            ("bamboohr", "BambooHR"),
                            ("ashby", "Ashby"),
                            ("jobvite", "Jobvite"),
                            ("smartrecruiters", "SmartRecruiters"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField(max_length=500, unique=True)),
                (
                    "external_requisition_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("company_name", models.CharField(db_index=True, max_length=255)),
                ("company_careers_url", models.URLField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("job_type", models.CharField(blank=True, max_length=50)),
                ("experience_level", models.CharField(blank=True, max_length=50)),
                ("remote_status", models.CharField(blank=True, max_length=50)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_currency", models.CharField(default="USD", max_length=3)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "job_category",
                    models.CharField(
                        choices=[
                            ("engineering", "Engineering/Tech"),
                            ("healthcare", "Healthcare"),
                            ("retail", "Retail"),
                            ("finance", "Finance"),
                            ("sales", "Sales"),
                            ("marketing", "Marketing"),
                            ("operations", "Operations"),
                            ("hr", "Human Resources"),
                            ("legal", "Legal"),
                            ("executive", "Executive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("date_first_seen", models.DateTimeField(auto_now_add=True)),
                ("date_last_seen", models.DateTimeField(auto_now=True)),
                ("date_posted_external", models.DateTimeField(blank=True, null=True)),
                ("date_removed", models.DateTimeField(blank=True, null=True)),
                ("description_hash", models.CharField(db_index=True, max_length=64)),
                ("title_hash", models.CharField(db_index=True, max_length=64)),
                ("repost_count", models.PositiveIntegerField(default=0)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("closed", "Closed"),
                            ("published", "Published to Board"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("published_to_board", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraped_source",
                        to="jobs.job",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraped_listings",
                        to="jobs.company",
                    ),
                ),
                (
                    "previous_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reposts",
                        to="jobs.scrapedjoblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scraped Job Listing",
                "verbose_name_plural": "Scraped Job Listings",
                "ordering": ["-date_last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ListingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("applied_got_response", "Applied - Got Response"),
                            ("applied_no_response", "Applied - No Response"),
                            ("listing_outdated", "Listing Appears Outdated"),
                            ("listing_spam", "Listing is Spam/Fake"),
                            ("company_not_hiring", "Company Confirmed Not Hiring"),
                            ("successfully_hired", "Got Hired Through This"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "days_to_response",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Days until response if applicable",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="jobs.scrapedjoblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing Feedback",
                "verbose_name_plural": "Listing Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HiringActivityScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveSmallIntegerField(
                        default=50, help_text="Score from 0-100"
                    ),
                ),
                (
                    "score_band",
                    models.CharField(
                        choices=[
                            ("very_active", "Very Active (80-100)"),
                            ("likely_active", "Likely Active (65-79)"),
                            ("uncertain", "Uncertain (50-64)"),
                            ("low_signal", "Low Signal (0-49)"),
                        ],
                        default="uncertain",
                        max_length=20,
                    ),
                ),
                (
                    "score_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Individual signal scores and contributions",
                    ),
                ),
                ("score_version", models.PositiveSmallIntegerField(default=1)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("published_to_board", models.BooleanField(default=False)),
                (
                    "listing",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_score",
                        to="jobs.scrapedjoblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hiring Activity Score",
                "verbose_name_plural": "Hiring Activity Scores",
                "ordering": ["-total_score"],
            },
        ),
        migrations.AddIndex(
            model_name="scrapedjoblisting",
            index=models.Index(
                fields=["company_name", "status"], name="jobs_scrape_company_e28694_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedjoblisting",
            index=models.Index(
                fields=["source_ats", "status"], name="jobs_scrape_source__ce1c27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedjoblisting",
            index=models.Index(
                fields=["date_last_seen", "status"],
                name="jobs_scrape_date_la_5ce125_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapedjoblisting",
            index=models.Index(
                fields=["published_to_board", "status"],
                name="jobs_scrape_publish_a72104_idx",
            ),
        ),
    ]
