# Generated by Django 6.0.1 on 2026-02-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_has_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenzjobsListing",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_column="id", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.TextField(db_column="title")),
                ("company", models.TextField(db_column="company")),
                (
                    "location",
                    models.TextField(blank=True, db_column="location", null=True),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                ("apply_url", models.TextField(blank=True, db_column="applyUrl", null=True)),
                ("source", models.TextField(db_column="source")),
                (
                    "source_id",
                    models.TextField(blank=True, db_column="sourceId", null=True),
                ),
                (
                    "source_url",
                    models.TextField(blank=True, db_column="sourceUrl", null=True),
                ),
                (
                    "salary_min",
                    models.IntegerField(blank=True, db_column="salaryMin", null=True),
                ),
                (
                    "salary_max",
                    models.IntegerField(blank=True, db_column="salaryMax", null=True),
                ),
                (
                    "salary_currency",
                    models.TextField(blank=True, db_column="salaryCurrency", null=True),
                ),
                (
                    "job_type",
                    models.TextField(blank=True, db_column="jobType", null=True),
                ),
                (
                    "experience_level",
                    models.TextField(
                        blank=True, db_column="experienceLevel", null=True
                    ),
                ),
                ("remote", models.BooleanField(db_column="remote", default=False)),
                (
                    "category",
                    models.TextField(blank=True, db_column="category", null=True),
                ),
                (
                    "classification_confidence",
                    models.FloatField(
                        blank=True, db_column="classificationConfidence", null=True
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, db_column="requirements", null=True),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, db_column="benefits", null=True),
                ),
                (
                    "company_logo",
                    models.TextField(blank=True, db_column="companyLogo", null=True),
                ),
                (
                    "company_website",
                    models.TextField(blank=True, db_column="companyWebsite", null=True),
                ),
                ("skills", models.JSONField(blank=True, db_column="skills", null=True)),
                (
                    "audience_tags",
                    models.JSONField(blank=True, db_column="audienceTags", null=True),
                ),
                ("is_active", models.BooleanField(db_column="isActive", default=True)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, db_column="postedAt", null=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_column="lastSeenAt", null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="updatedAt", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_column="createdAt", null=True),
                ),
                (
                    "publisher",
                    models.TextField(blank=True, db_column="publisher", null=True),
                ),
                (
                    "is_rjrp_verified",
                    models.BooleanField(db_column="isRjrpVerified", default=False),
                ),
                (
                    "rjrp_employer_id",
                    models.TextField(
                        blank=True, db_column="rjrpEmployerId", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "genzjobs Listing",
                "verbose_name_plural": "genzjobs Listings",
                "db_table": "job_listings",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="classification_confidence",
            field=models.FloatField(
                blank=True, help_text="ML classification confidence 0-1", null=True
            ),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="genzjobs_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="CUID from genzjobs job_listings table",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="has_benefits",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="has_company_logo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="has_company_website",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="has_requirements",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text="Original publisher/source from genzjobs",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="skills_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scrapedjoblisting",
            name="date_last_seen",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="scrapedjoblisting",
            name="source_ats",
            field=models.CharField(
                choices=[
                    ("greenhouse", "Greenhouse"),
                    ("lever", "Lever"),
                    ("workday", "Workday"),
                    ("icims", "iCIMS"),
                    ("taleo", "Taleo"),
                    ("bamboohr", "BambooHR"),
                    ("ashby", "Ashby"),
                    ("jobvite", "Jobvite"),
                    ("smartrecruiters", "SmartRecruiters"),
                    ("remotive", "Remotive"),
                    ("usajobs", "USAJobs"),
                    ("jsearch", "JSearch"),
                    ("arbeitnow", "Arbeitnow"),
                    ("jobicy", "Jobicy"),
                    ("whoishiring", "Who Is Hiring"),
                    ("direct_ats", "Direct ATS"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="scrapedjoblisting",
            name="source_url",
            field=models.URLField(db_index=True, max_length=500),
        ),
    ]
