# Generated by Django 6.0.1 on 2026-03-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0019_genzjobs_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="link_last_checked",
            field=models.DateTimeField(
                blank=True, help_text="When the source URL was last verified", null=True
            ),
        ),
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="link_status_code",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Last HTTP status code from source URL", null=True
            ),
        ),
    ]
