# Generated by Django 5.1.4 on 2026-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_add_link_health_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapedjoblisting",
            name="description_summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated concise summary of the job description",
            ),
        ),
    ]
