# Generated by Django 5.2.9 on 2026-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0022_industry_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialContentDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("platform", models.CharField(default="linkedin", max_length=30)),
                ("draft_text", models.TextField()),
                (
                    "source_metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of the data points that informed this draft (for traceability back to the numbers)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("posted", "Posted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Content Draft",
                "verbose_name_plural": "Social Content Drafts",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyGhostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("industry_category", models.CharField(max_length=50)),
                ("total_listings", models.PositiveIntegerField(default=0)),
                (
                    "above_threshold_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Listings scoring >= publish threshold (65)",
                    ),
                ),
                (
                    "below_threshold_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Listings scoring < publish threshold (65)"
                    ),
                ),
                (
                    "ghost_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of listings scoring below threshold",
                        max_digits=5,
                    ),
                ),
                (
                    "avg_has",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "median_has",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "salary_transparency_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of listings with salary_min or salary_max present",
                        max_digits=5,
                    ),
                ),
                (
                    "repost_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of listings flagged with 3+ reposts (repost_count >= 3)",
                        max_digits=5,
                    ),
                ),
                (
                    "evergreen_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% open 90+ days with no updates (repost_count == 0) — matches the HAS evergreen_penalty signal",
                        max_digits=5,
                    ),
                ),
                (
                    "staleness_buckets",
                    models.JSONField(
                        default=dict,
                        help_text='{"0_14d": N, "15_30d": N, "31_60d": N, "61_90d": N, "90d_plus": N}',
                    ),
                ),
                (
                    "new_listings_today",
                    models.PositiveIntegerField(
                        default=0, help_text="Listings first seen in the last 24 hours"
                    ),
                ),
                (
                    "new_listings_avg_has",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average HAS of today's new listings (null if none)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "threshold_crossings_down",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Listings that were >= 65 yesterday but < 65 today",
                    ),
                ),
                (
                    "top_movers",
                    models.JSONField(
                        default=dict,
                        help_text='{"up": [{"company", "delta", "current_avg"}], "down": [...]} — top 5 each direction by avg-HAS change vs prior day',
                    ),
                ),
                (
                    "previous_ghost_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prior day's ghost_rate for this industry (null on first day)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Daily Ghost Report",
                "verbose_name_plural": "Daily Ghost Reports",
                "ordering": ["-date", "industry_category"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "industry_category"),
                        name="uniq_report_date_industry",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyScoreSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "listing_id",
                    models.PositiveIntegerField(
                        help_text="ScrapedJobListing PK at snapshot time (not a live FK)"
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "industry_category",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("total_score", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Daily Score Snapshot",
                "verbose_name_plural": "Daily Score Snapshots",
                "indexes": [
                    models.Index(
                        fields=["date", "industry_category"],
                        name="jobs_dailys_date_5796ce_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "listing_id"), name="uniq_snapshot_date_listing"
                    )
                ],
            },
        ),
    ]
