# Generated by Django 5.1.4 on 2026-03-09 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedEmployer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="directory/logos/"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="One-liner for card display",
                        max_length=300,
                    ),
                ),
                ("headquarters", models.CharField(blank=True, max_length=200)),
                (
                    "employee_count",
                    models.CharField(
                        blank=True, help_text='e.g. "180,000+ employees"', max_length=50
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("tech", "Tech"),
                            ("finance", "Finance/Banking"),
                            ("healthcare", "Healthcare"),
                            ("aerospace", "Aerospace/Defense"),
                            ("government", "Government"),
                            ("consulting", "Consulting"),
                            ("retail", "Retail"),
                            ("energy", "Energy"),
                            ("pharma", "Pharma"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "career_url",
                    models.URLField(help_text="Career portal base URL", max_length=500),
                ),
                (
                    "url_pattern",
                    models.CharField(
                        help_text="URL template: {base_url}?q={query}&location={location}",
                        max_length=500,
                    ),
                ),
                (
                    "supports_location",
                    models.BooleanField(
                        default=False,
                        help_text="Does the career URL support a location parameter?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "display_priority",
                    models.IntegerField(
                        default=100, help_text="Lower = higher priority in results"
                    ),
                ),
                (
                    "estimated_open_roles",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("last_count_update", models.DateTimeField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "verified_employer",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to verified employer account if they have claimed this page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="featured_employer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="JobTitleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_title", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "search_aliases",
                    models.JSONField(
                        default=list,
                        help_text="List of search terms that map to this canonical title",
                    ),
                ),
                (
                    "related_titles",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Related canonical titles for "you might also like"',
                        to="directory.jobtitlemapping",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job title mappings",
                "ordering": ["canonical_title"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_query", models.CharField(blank=True, max_length=300)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("search_results", "Search Results"),
                            ("directory_page", "Directory Page"),
                            ("employer_detail", "Employer Detail"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="directory.featuredemployer",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="directory.jobtitlemapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DirectoryEmployerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("canonical_category", models.CharField(max_length=200)),
                (
                    "employer_search_term",
                    models.CharField(
                        blank=True,
                        help_text="What to pass as query on this employer's career site",
                        max_length=200,
                    ),
                ),
                ("estimated_count", models.PositiveIntegerField(blank=True, null=True)),
                ("last_count_update", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="directory.featuredemployer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Directory employer categories",
                "ordering": ["-estimated_count"],
                "unique_together": {("employer", "canonical_category")},
            },
        ),
        migrations.CreateModel(
            name="EmployerTitleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_search_term",
                    models.CharField(
                        help_text="Employer's preferred search term for this role",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_overrides",
                        to="directory.featuredemployer",
                    ),
                ),
                (
                    "canonical_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_overrides",
                        to="directory.jobtitlemapping",
                    ),
                ),
            ],
            options={
                "unique_together": {("employer", "canonical_title")},
            },
        ),
    ]
