# Generated by Django 5.1.4 on 2026-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredemployer",
            name="link_consecutive_failures",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="featuredemployer",
            name="link_healthy",
            field=models.BooleanField(
                default=True, help_text="Auto-updated by check_directory_links command"
            ),
        ),
        migrations.AddField(
            model_name="featuredemployer",
            name="link_last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featuredemployer",
            name="link_status_code",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
